services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports: 
      - "${API_PORT}:8000"
    command: "uvicorn --factory presentation.api.main:create_app --host 0.0.0.0 --port 8000 --workers 4"

    env_file:
      - ../.env
    volumes:
      - ../app:/app/
    networks:
      - backend

networks:
  backend:
    driver: bridge