"""add competition status

Revision ID: 655f1502e8f3
Revises: 2c3b8b54594a
Create Date: 2024-09-28 07:07:31.570455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '655f1502e8f3'
down_revision: Union[str, None] = '2c3b8b54594a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'is_completed')
    # ### end Alembic commands ###
