"""on delete cascade CompetitionSwaps

Revision ID: 8d36fb495487
Revises: 5688101c26d8
Create Date: 2024-10-07 22:30:43.766869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d36fb495487'
down_revision: Union[str, None] = '5688101c26d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('competition_swaps_competition_id_fkey', 'competition_swaps', type_='foreignkey')
    op.create_foreign_key(None, 'competition_swaps', 'competitions', ['competition_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competition_swaps', type_='foreignkey')
    op.create_foreign_key('competition_swaps_competition_id_fkey', 'competition_swaps', 'competitions', ['competition_id'], ['id'])
    # ### end Alembic commands ###
